CC = gcc
CFLAGS = -Wall -Wextra -Werror
TARGET = libft.a
SRCS = ./srcs/ft_putchar.c ./srcs/ft_swap.c ./srcs/ft_putstr.c ./srcs/ft_strlen.c ./srcs/ft_strcmp.c
OBJECTS = ft_putchar.o ft_swap.o ft_putstr.o ft_strlen.o ft_strlen.o
INC = ./includes/ft.h

$(OBJECTS): $(SRCS)
	$(CC) -o $(CFLAGS) $@ $^
